# Generated by Django 5.2.9 on 2025-12-06 08:54

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting account.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('user_type', models.CharField(choices=[('customer', 'customer'), ('stylist', 'stylist'), ('salon_owner', 'salon_owner'), ('admin', 'admin')], default='customer', max_length=20)),
                ('mobile', models.CharField(blank=True, max_length=11, unique=True, validators=[django.core.validators.RegexValidator(message='Mobile number must be in the format 09xxxxxxxxxx', regex='^09\\d{9}$')], verbose_name='phone number')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('is_phone_verified', models.BooleanField(default=False, verbose_name='verified phone number')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='OTPCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=11, null=True, verbose_name='phone number')),
                ('code', models.CharField(blank=True, max_length=6, null=True, verbose_name='code')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='created at')),
            ],
            options={
                'verbose_name': 'otp code',
                'verbose_name_plural': 'otp codes',
            },
        ),
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='user')),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female'), ('other', 'other')], default='other', max_length=10)),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='birth date')),
                ('address', models.TextField(blank=True, null=True, verbose_name='address')),
                ('city', models.CharField(blank=True, max_length=20, null=True, verbose_name='city')),
                ('postal_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='postal code')),
                ('phone', models.CharField(blank=True, max_length=11, null=True, verbose_name='phone number')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='email address')),
                ('phone_notification', models.BooleanField(default=False, verbose_name='phone notification')),
                ('email_notification', models.BooleanField(default=False, verbose_name='email notification')),
            ],
            options={
                'verbose_name': 'customer profile',
                'verbose_name_plural': 'customer profiles',
            },
        ),
        migrations.CreateModel(
            name='SalonOwnerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female'), ('other', 'other')], default='other', max_length=10)),
                ('business_phone', models.CharField(blank=True, max_length=11, null=True, verbose_name='phone number')),
                ('business_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='email address')),
                ('national_id', models.CharField(blank=True, max_length=11, null=True, verbose_name='national id')),
                ('business_license', models.CharField(blank=True, max_length=50, null=True, verbose_name='license code')),
                ('is_card_image', models.ImageField(blank=True, null=True, upload_to='documents/id_cards', verbose_name='id_card')),
                ('license_image', models.ImageField(blank=True, null=True, upload_to='documents/licenses', verbose_name='licenses image')),
                ('is_verified', models.BooleanField(default=False, verbose_name='verified')),
                ('verified_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='verified at')),
                ('bank_account', models.CharField(blank=True, max_length=16, null=True, verbose_name='bank account')),
                ('shaba_number', models.CharField(blank=True, max_length=24, null=True, verbose_name='shaba number')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='salon_owner_profile', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'owner profile',
                'verbose_name_plural': 'owner profiles',
            },
        ),
        migrations.CreateModel(
            name='StylistProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female'), ('other', 'other')], default='other', max_length=10, verbose_name='gender')),
                ('experience_years', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='experience years')),
                ('bio', models.TextField(blank=True, help_text='Descriptions about hairdressers and specialties', null=True, verbose_name='bio')),
                ('certificates', models.FileField(blank=True, help_text='List of certificates and documents', null=True, upload_to='certificates', verbose_name='certificates')),
                ('resume', models.FileField(blank=True, help_text='Resume document', null=True, upload_to='resume', verbose_name='resume')),
                ('is_active', models.BooleanField(default=False, verbose_name='active')),
                ('is_verified', models.BooleanField(default=False, verbose_name='verified')),
                ('rating_average', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=3, null=True, verbose_name='rating average')),
                ('rating_count', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='rating count')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stylist_profile', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'stylist profile',
                'verbose_name_plural': 'stylist profiles',
            },
        ),
    ]
