# Generated by Django 5.2.9 on 2025-12-06 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Salon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='name')),
                ('slug', models.SlugField(blank=True, max_length=100, null=True, verbose_name='slug')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('gender_type', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='Male', max_length=20)),
                ('address', models.TextField(blank=True, null=True, verbose_name='address')),
                ('city', models.TextField(blank=True, max_length=100, null=True, verbose_name='city')),
                ('province', models.TextField(blank=True, max_length=100, null=True, verbose_name='province')),
                ('country', models.TextField(blank=True, max_length=100, null=True, verbose_name='country')),
                ('postal_code', models.TextField(blank=True, max_length=100, null=True, verbose_name='postal code')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='logo')),
                ('has_parking', models.BooleanField(blank=True, default=False, null=True, verbose_name='has_parking')),
                ('has_wifi', models.BooleanField(blank=True, default=False, null=True, verbose_name='has_wifi')),
                ('has_food', models.BooleanField(blank=True, default=False, null=True, verbose_name='has_food')),
                ('has_kids_area', models.BooleanField(blank=True, default=False, null=True, verbose_name='has_kids_area')),
                ('rating_average', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=2, null=True, verbose_name='rating_average')),
                ('rating_count', models.IntegerField(blank=True, default=0, null=True, verbose_name='rating_count')),
                ('is_active', models.BooleanField(blank=True, default=True, null=True, verbose_name='is_active')),
                ('is_verified', models.BooleanField(blank=True, default=False, null=True, verbose_name='is_verified')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='updated_at')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.salonownerprofile')),
            ],
            options={
                'verbose_name': 'Salon',
                'verbose_name_plural': 'Salon',
                'ordering': ['-created_at'],
            },
        ),
    ]
