# Generated by Django 5.2.9 on 2025-12-06 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='name')),
                ('slug', models.SlugField(blank=True, max_length=100, null=True, verbose_name='slug')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='icon')),
                ('is_active', models.BooleanField(blank=True, default=True, null=True, verbose_name='is_active')),
            ],
            options={
                'verbose_name': 'ServiceCategory',
                'verbose_name_plural': 'ServiceCategory',
            },
        ),
        migrations.CreateModel(
            name='SalonImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='image')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='updated_at')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='title')),
                ('slug', models.SlugField(blank=True, max_length=100, null=True, verbose_name='slug')),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salon.salon')),
            ],
            options={
                'verbose_name': 'SalonImage',
                'verbose_name_plural': 'SalonImage',
                'ordering': ['-created_at'],
            },
        ),
    ]
