# Generated by Django 5.2.9 on 2025-12-06 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0003_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkingHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.IntegerField(blank=True, choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], null=True, verbose_name='weekday')),
                ('opening_time', models.TimeField(blank=True, null=True, verbose_name='opening_time')),
                ('closing_time', models.TimeField(blank=True, null=True, verbose_name='closing_time')),
                ('is_closed', models.BooleanField(blank=True, default=False, null=True, verbose_name='is_closed')),
                ('salon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='working_hours', to='salon.salon', verbose_name='salon')),
            ],
            options={
                'verbose_name': 'Working Hours',
                'verbose_name_plural': 'Working Hours',
            },
        ),
    ]
