# Generated by Django 5.2.9 on 2025-12-06 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('salon', '0004_workinghours'),
    ]

    operations = [
        migrations.CreateModel(
            name='StylistSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.IntegerField(blank=True, choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], null=True, verbose_name='weekday')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='start_time')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='end_time')),
                ('stylist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.stylistprofile', verbose_name='stylist')),
            ],
            options={
                'verbose_name': 'Stylist Schedule',
                'verbose_name_plural': 'Stylist Schedule',
                'ordering': ['-start_time'],
            },
        ),
    ]
