# Generated by Django 5.2.9 on 2025-12-06 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0005_stylistschedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalonSpecialDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True, verbose_name='date')),
                ('is_closed', models.BooleanField(blank=True, default=False, null=True, verbose_name='is_closed')),
                ('opening_time', models.TimeField(blank=True, null=True, verbose_name='opening_time')),
                ('closing_time', models.TimeField(blank=True, null=True, verbose_name='closing_time')),
                ('reason', models.TextField(blank=True, null=True, verbose_name='reason')),
                ('salon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='special_days', to='salon.salon', verbose_name='salon')),
            ],
            options={
                'verbose_name': 'Salon Special Day',
                'verbose_name_plural': 'Salon Special Day',
                'ordering': ['-date'],
            },
        ),
    ]
