# Generated by Django 5.2.9 on 2025-12-06 18:02

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cart', '0003_address_shoppingmethod'),
        ('reservation', '0003_reservationpolicy_reservationreminder'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentGateway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('zarinpal', 'زرین\u200cپال'), ('idpay', 'آیدی\u200cپی'), ('nextpay', 'نکست\u200cپی'), ('payir', 'پی'), ('saman', 'سامان'), ('mellat', 'ملت'), ('parsian', 'پارسیان')], max_length=50, unique=True, verbose_name='نام درگاه')),
                ('display_name', models.CharField(max_length=100, verbose_name='نام نمایشی')),
                ('merchant_id', models.CharField(max_length=200, verbose_name='مرچنت کد')),
                ('api_key', models.CharField(blank=True, max_length=200, null=True, verbose_name='API Key')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='payment_gateways/', verbose_name='لوگو')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('is_default', models.BooleanField(default=False, verbose_name='پیش\u200cفرض')),
                ('total_transactions', models.PositiveIntegerField(default=0, verbose_name='تعداد تراکنش\u200cها')),
                ('successful_transactions', models.PositiveIntegerField(default=0, verbose_name='تراکنش\u200cهای موفق')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
            ],
            options={
                'verbose_name': 'درگاه پرداخت',
                'verbose_name_plural': 'درگاه\u200cهای پرداخت',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_number', models.CharField(max_length=20, unique=True, verbose_name='شماره پرداخت')),
                ('payment_type', models.CharField(choices=[('order', 'خرید محصول'), ('reservation', 'رزرواسیون')], max_length=20, verbose_name='نوع پرداخت')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='مبلغ (تومان)')),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('processing', 'در حال پردازش'), ('success', 'موفق'), ('failed', 'ناموفق'), ('cancelled', 'لغو شده'), ('refunded', 'بازگشت داده شده')], default='pending', max_length=20, verbose_name='وضعیت')),
                ('authority', models.CharField(blank=True, max_length=200, null=True, verbose_name='کد Authority')),
                ('ref_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='کد رهگیری')),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='شناسه تراکنش')),
                ('card_number', models.CharField(blank=True, max_length=16, null=True, verbose_name='شماره کارت')),
                ('card_hash', models.CharField(blank=True, max_length=100, null=True, verbose_name='هش کارت')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='پیام خطا')),
                ('error_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='کد خطا')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='آی\u200cپی')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ پرداخت')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='cart.order', verbose_name='سفارش')),
                ('reservation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='reservation.reservation', verbose_name='رزرو')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
                ('gateway', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='payment.paymentgateway', verbose_name='درگاه پرداخت')),
            ],
            options={
                'verbose_name': 'پرداخت',
                'verbose_name_plural': 'پرداخت\u200cها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refund_number', models.CharField(max_length=20, unique=True, verbose_name='شماره بازگشت')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='مبلغ بازگشت (تومان)')),
                ('reason', models.CharField(choices=[('customer_request', 'درخواست مشتری'), ('order_cancelled', 'لغو سفارش'), ('duplicate_payment', 'پرداخت تکراری'), ('technical_issue', 'مشکل فنی'), ('other', 'سایر')], max_length=50, verbose_name='دلیل بازگشت')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('status', models.CharField(choices=[('pending', 'در انتظار بررسی'), ('approved', 'تایید شده'), ('rejected', 'رد شده'), ('processing', 'در حال پردازش'), ('completed', 'انجام شده')], default='pending', max_length=20, verbose_name='وضعیت')),
                ('refund_ref_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='کد رهگیری بازگشت')),
                ('admin_note', models.TextField(blank=True, null=True, verbose_name='یادداشت مدیر')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ درخواست')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ تایید')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ انجام')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='payment.payment', verbose_name='پرداخت')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_refunds', to=settings.AUTH_USER_MODEL, verbose_name='پردازش شده توسط')),
            ],
            options={
                'verbose_name': 'بازگشت وجه',
                'verbose_name_plural': 'بازگشت وجوه',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_number', models.CharField(max_length=20, unique=True, verbose_name='شماره تراکنش')),
                ('transaction_type', models.CharField(choices=[('payment', 'پرداخت'), ('refund', 'بازگشت وجه'), ('commission', 'کمیسیون'), ('settlement', 'تسویه')], max_length=20, verbose_name='نوع تراکنش')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='مبلغ (تومان)')),
                ('balance_before', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='موجودی قبل')),
                ('balance_after', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='موجودی بعد')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ تراکنش')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='payment.payment', verbose_name='پرداخت')),
                ('refund', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='payment.refund', verbose_name='بازگشت وجه')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'تراکنش',
                'verbose_name_plural': 'تراکنش\u200cها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='موجودی (تومان)')),
                ('total_earned', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='مجموع درآمد')),
                ('total_withdrawn', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='مجموع برداشت')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'کیف پول',
                'verbose_name_plural': 'کیف پول\u200cها',
            },
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['payment_number'], name='payment_pay_payment_67e9d9_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['ref_id'], name='payment_pay_ref_id_3b7b58_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status'], name='payment_pay_status_124d3d_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['transaction_number'], name='payment_tra_transac_014686_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['user', '-created_at'], name='payment_tra_user_id_01aff8_idx'),
        ),
    ]
