# Generated by Django 5.2.9 on 2025-12-06 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('slug', models.SlugField(verbose_name='slug')),
                ('content', models.TextField(blank=True, null=True, verbose_name='content')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('show_in_menu', models.BooleanField(default=True, verbose_name='show in menu')),
                ('order', models.IntegerField(default=0, verbose_name='order')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'صفحه',
                'verbose_name_plural': 'صفحات',
                'ordering': ['order', 'title'],
            },
        ),
    ]
