# Generated by Django 5.2.9 on 2025-12-06 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='full name')),
                ('email', models.EmailField(max_length=100, verbose_name='email')),
                ('phone_number', models.CharField(max_length=100, verbose_name='phone number')),
                ('subject', models.CharField(max_length=100, verbose_name='subject')),
                ('message', models.TextField(verbose_name='message')),
                ('status', models.CharField(choices=[('new', 'جدید'), ('in_progress', 'در حال بررسی'), ('answered', 'پاسخ داده شده'), ('closed', 'بسته شده')], max_length=100, verbose_name='status')),
                ('response', models.CharField(max_length=100, verbose_name='response')),
                ('response_at', models.DateTimeField(auto_now_add=True, verbose_name='response at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
            ],
            options={
                'verbose_name': 'پیام تماس',
                'verbose_name_plural': 'پیام\u200cهای تماس',
                'ordering': ['-created_at'],
            },
        ),
    ]
