# Generated by Django 5.2.9 on 2025-12-06 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_contactmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('subtitle', models.CharField(blank=True, max_length=300, null=True, verbose_name='زیرعنوان')),
                ('main_content', models.TextField(verbose_name='محتوای اصلی')),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='about/', verbose_name='تصویر اصلی')),
                ('total_salons', models.PositiveIntegerField(default=0, verbose_name='تعداد آرایشگاه\u200cها')),
                ('total_stylists', models.PositiveIntegerField(default=0, verbose_name='تعداد آرایشگران')),
                ('total_customers', models.PositiveIntegerField(default=0, verbose_name='تعداد مشتریان')),
                ('total_reservations', models.PositiveIntegerField(default=0, verbose_name='تعداد رزروها')),
                ('company_name', models.CharField(max_length=200, verbose_name='نام شرکت')),
                ('phone', models.CharField(max_length=11, verbose_name='تلفن')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل')),
                ('address', models.TextField(verbose_name='آدرس')),
                ('instagram', models.URLField(blank=True, null=True, verbose_name='اینستاگرام')),
                ('telegram', models.URLField(blank=True, null=True, verbose_name='تلگرام')),
                ('whatsapp', models.CharField(blank=True, max_length=11, null=True, verbose_name='واتساپ')),
                ('linkedin', models.URLField(blank=True, null=True, verbose_name='لینکدین')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
            ],
            options={
                'verbose_name': 'درباره ما',
                'verbose_name_plural': 'درباره ما',
            },
        ),
    ]
