# Generated by Django 5.2.9 on 2025-12-06 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_teammember'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=200, verbose_name='نام سایت')),
                ('site_tagline', models.CharField(max_length=300, verbose_name='شعار سایت')),
                ('site_description', models.TextField(verbose_name='توضیحات سایت')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='site/', verbose_name='لوگو')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='site/', verbose_name='فاویکون')),
                ('contact_email', models.EmailField(max_length=254, verbose_name='ایمیل تماس')),
                ('contact_phone', models.CharField(max_length=11, verbose_name='تلفن تماس')),
                ('support_phone', models.CharField(blank=True, max_length=11, null=True, verbose_name='تلفن پشتیبانی')),
                ('instagram', models.URLField(blank=True, null=True, verbose_name='اینستاگرام')),
                ('telegram', models.URLField(blank=True, null=True, verbose_name='تلگرام')),
                ('whatsapp', models.CharField(blank=True, max_length=11, null=True, verbose_name='واتساپ')),
                ('google_analytics_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='کد Google Analytics')),
                ('site_active', models.BooleanField(default=True, verbose_name='سایت فعال')),
                ('maintenance_mode', models.BooleanField(default=False, verbose_name='حالت تعمیر و نگهداری')),
                ('maintenance_message', models.TextField(blank=True, null=True, verbose_name='پیام حالت تعمیر')),
                ('platform_commission_percentage', models.DecimalField(decimal_places=2, default=10.0, max_digits=5, verbose_name='درصد کمیسیون پلتفرم')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
            ],
            options={
                'verbose_name': 'تنظیمات سایت',
                'verbose_name_plural': 'تنظیمات سایت',
            },
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('subtitle', models.CharField(blank=True, max_length=300, null=True, verbose_name='زیرعنوان')),
                ('image', models.ImageField(upload_to='sliders/', verbose_name='تصویر')),
                ('button_text', models.CharField(blank=True, max_length=50, null=True, verbose_name='متن دکمه')),
                ('button_link', models.CharField(blank=True, max_length=200, null=True, verbose_name='لینک دکمه')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
            ],
            options={
                'verbose_name': 'اسلاید',
                'verbose_name_plural': 'اسلایدر',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=200, verbose_name='نام مشتری')),
                ('customer_position', models.CharField(blank=True, max_length=100, null=True, verbose_name='سمت/شغل')),
                ('content', models.TextField(verbose_name='متن نظر')),
                ('rating', models.PositiveIntegerField(default=5, help_text='از 1 تا 5', verbose_name='امتیاز')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='testimonials/', verbose_name='عکس')),
                ('is_featured', models.BooleanField(default=False, verbose_name='نمایش در صفحه اصلی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
            ],
            options={
                'verbose_name': 'نظر مشتری',
                'verbose_name_plural': 'نظرات مشتریان',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
