# Generated by Django 5.2.9 on 2025-12-06 14:50

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_productattribute'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=10, null=True, verbose_name='Code')),
                ('discount_type', models.CharField(blank=True, max_length=10, null=True, verbose_name='Discount type')),
                ('value', models.CharField(blank=True, max_length=10, null=True, verbose_name='Value')),
                ('usage_limit', models.PositiveIntegerField(default=0, verbose_name='Usage limit')),
                ('usage_limit_per_user', models.PositiveIntegerField(default=0, verbose_name='Usage limit per user')),
                ('valid_from', models.DateTimeField(blank=True, null=True, verbose_name='Valid from')),
                ('valid_to', models.DateTimeField(blank=True, null=True, verbose_name='Valid to')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('applicable_products', models.ManyToManyField(blank=True, related_name='applicable_products', to='shop.product', verbose_name='Applicable products')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.product', verbose_name='product')),
            ],
            options={
                'verbose_name': 'discount',
                'verbose_name_plural': 'discounts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductVariation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Name')),
                ('sku', models.CharField(blank=True, max_length=100, null=True, verbose_name='SKU')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('price', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Price')),
                ('stock', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Stock')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.product', verbose_name='product')),
            ],
            options={
                'verbose_name': 'product variation',
                'verbose_name_plural': 'product variations',
                'ordering': ['product'],
            },
        ),
    ]
