# Generated by Django 5.2.9 on 2025-12-06 17:57

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('cart', '0002_orderitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='نام گیرنده')),
                ('phone', models.CharField(max_length=11, verbose_name='تلفن')),
                ('address', models.TextField(verbose_name='آدرس کامل')),
                ('city', models.CharField(max_length=100, verbose_name='شهر')),
                ('province', models.CharField(max_length=100, verbose_name='استان')),
                ('postal_code', models.CharField(max_length=10, verbose_name='کد پستی')),
                ('is_default', models.BooleanField(default=False, verbose_name='آدرس پیش\u200cفرض')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='account.customerprofile', verbose_name='مشتری')),
            ],
            options={
                'verbose_name': 'آدرس',
                'verbose_name_plural': 'آدرس\u200cها',
                'ordering': ['-is_default', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShoppingMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='shopping method name')),
                ('shopping_method', models.CharField(max_length=120)),
                ('description', models.CharField(max_length=120, verbose_name='shopping method description')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='cost')),
                ('estimated_days_min', models.PositiveIntegerField(default=0, verbose_name='Minimum delivery time (days)')),
                ('estimated_days_max', models.PositiveIntegerField(default=0, verbose_name='Maximum delivery time (days)')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.order')),
            ],
            options={
                'verbose_name': 'ShoppingMethod',
                'verbose_name_plural': 'ShoppingMethods',
            },
        ),
    ]
