# Generated by Django 5.2.9 on 2025-12-06 12:26

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_reservation'),
        ('salon', '0006_salonspecialday'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservationPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('free_canceling_hours', models.PositiveSmallIntegerField(default=24, validators=[django.core.validators.MinValueValidator(24)], verbose_name='free_canceling_hours')),
                ('canceling_free_percentage', models.PositiveSmallIntegerField(default=0, help_text='Percentage of the reservation amount that will be deducted as a penalty', verbose_name='canceling_free_percentage')),
                ('policy_text', models.TextField(blank=True, help_text='The text of the reservation policy', verbose_name='policy_text')),
                ('is_active', models.BooleanField(default=True)),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salon.salon')),
            ],
            options={
                'verbose_name': 'reservation policy',
                'verbose_name_plural': 'reservation policies',
            },
        ),
        migrations.CreateModel(
            name='ReservationReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_type', models.CharField(choices=[('sms', 'sms'), ('email', 'email'), ('notify', 'notify')], max_length=10, verbose_name='reminder_type')),
                ('hour_before', models.PositiveIntegerField(default=24, validators=[django.core.validators.MinValueValidator(24)], verbose_name='hour_before')),
                ('schedule_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='schedule_time')),
                ('is_sent', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='sent_at')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservation.reservation')),
            ],
            options={
                'verbose_name': 'reminder',
                'verbose_name_plural': 'reminders',
            },
        ),
    ]
